import 'package:flutter/material.dart';
import '../services/app_settings.dart';

/// Sistema de strings localizados (ES/EN/PT) para los textos visibles
/// más relevantes de la app: navegación, títulos, secciones, botones
/// y mensajes de estado vacío.
class AppStrings {
  static const Map<String, Map<String, String>> _all = {
    'es': {
      // Navegación
      'inicio': 'Inicio',
      'pedidos': 'Pedidos',
      'momento': 'Momento',
      'perfil': 'Perfil',
      // Saludos
      'hola': 'Hola',
      // Pantallas cliente
      'mis_pedidos': 'Mis pedidos',
      'mis_facturas': 'Mis facturas',
      'tus_recibos': 'Tus recibos',
      'tus_facturas': 'Tus facturas',
      'historial_compras': 'Historial de tus compras',
      'seguimiento_vivo': 'SEGUIMIENTO EN VIVO',
      'en_preparacion': 'EN PREPARACIÓN',
      'historial_hoy': 'HISTORIAL DE HOY',
      'total_hoy': 'TOTAL HOY',
      'sin_pedidos': 'Aún no tienes pedidos',
      'sin_pedidos_msg':
          'Cuando hagas tu primer pedido,\naparecerá aquí en tiempo real.',
      'explorar_menu': 'EXPLORAR MENÚ',
      'sugerencia': 'SUGERENCIA PARA TI',
      'momento_ideal': 'Momento ideal',
      'prediccion_afluencia': 'PREDICCIÓN DE AFLUENCIA · HOY',
      'sin_datos': 'Aún sin datos suficientes',
      'sin_datos_cliente':
          'Tras tu primera visita, te mostraremos\nlas mejores horas para ir al restaurante.',
      'mejor_hora': 'MEJOR HORA SUGERIDA',
      'tendencia_semana': 'TENDENCIA DE LA SEMANA',
      'espera_promedio': 'ESPERA PROMEDIO',
      'mesas_libres': 'MESAS LIBRES',
      'destacados_hoy': 'Destacados de hoy',
      'recomendados_ti': 'Recomendados para ti',
      'categorias': 'Categorías',
      'ver_todos': 'Ver todos',
      'oferta_hoy': 'OFERTA HOY',
      'reservar_mesa': 'Reservar\nmesa',
      'pedido_domicilio': 'Pedido a\ndomicilio',
      'promos_dia': 'Promos\ndel día',
      'buscar_placeholder': 'Buscar platos, restaurantes...',
      // Perfil
      'cuenta': 'CUENTA',
      'preferencias': 'PREFERENCIAS',
      'soporte': 'SOPORTE',
      'cerrar_sesion': 'Cerrar sesión',
      'cliente_desde': 'Cliente desde',
      'visitas': 'VISITAS',
      'calif_prom': 'CALIF. PROM.',
      'favoritos': 'Favoritos',
      'metodos_pago': 'Métodos de pago',
      'direcciones': 'Direcciones',
      'idioma': 'Idioma',
      'apariencia': 'Apariencia',
      'notificaciones': 'Notificaciones',
      'ayuda': 'Centro de ayuda',
      'privacidad': 'Privacidad',
      'acerca_de': 'Acerca de',
      'miembro': 'MIEMBRO',
      // Admin
      'panel': 'Panel',
      'analisis': 'Análisis',
      'negocio': 'Negocio',
      'mi_negocio': 'Mi negocio',
      'gestion_restaurante': 'GESTIÓN DEL RESTAURANTE',
      'tu_restaurante': 'TU RESTAURANTE',
      'tus_datos': 'TUS DATOS',
      'gestion_negocio': 'GESTIÓN DEL NEGOCIO',
      'operaciones': 'OPERACIONES',
      'configuracion': 'CONFIGURACIÓN',
      'administrador': 'ADMINISTRADOR',
      'resumen_hoy': 'Resumen de hoy',
      'ventas_hoy': 'Ventas hoy',
      'pedidos_activos': 'Pedidos activos',
      'mesas_ocupadas': 'Mesas ocupadas',
      'clientes_hoy': 'Clientes hoy',
      'pedidos_recientes': 'Pedidos recientes',
      'sin_datos_admin':
          'A medida que recibas pedidos, aquí verás\nlas predicciones y métricas.',
    },
    'en': {
      'inicio': 'Home',
      'pedidos': 'Orders',
      'momento': 'Timing',
      'perfil': 'Profile',
      'hola': 'Hi',
      'mis_pedidos': 'My orders',
      'mis_facturas': 'My invoices',
      'tus_recibos': 'Your receipts',
      'tus_facturas': 'Your invoices',
      'historial_compras': 'History of your purchases',
      'seguimiento_vivo': 'LIVE TRACKING',
      'en_preparacion': 'IN PROGRESS',
      'historial_hoy': "TODAY'S HISTORY",
      'total_hoy': 'TODAY TOTAL',
      'sin_pedidos': 'No orders yet',
      'sin_pedidos_msg':
          'When you place your first order,\nit will show up here in real time.',
      'explorar_menu': 'EXPLORE MENU',
      'sugerencia': 'PICK FOR YOU',
      'momento_ideal': 'Best time',
      'prediccion_afluencia': 'CROWD FORECAST · TODAY',
      'sin_datos': 'Not enough data yet',
      'sin_datos_cliente':
          "After your first visit, we'll show\nyou the best times to come.",
      'mejor_hora': 'BEST SUGGESTED HOUR',
      'tendencia_semana': 'WEEKLY TREND',
      'espera_promedio': 'AVG WAIT',
      'mesas_libres': 'FREE TABLES',
      'destacados_hoy': "Today's highlights",
      'recomendados_ti': 'Recommended for you',
      'categorias': 'Categories',
      'ver_todos': 'See all',
      'oferta_hoy': "TODAY'S OFFER",
      'reservar_mesa': 'Book a\ntable',
      'pedido_domicilio': 'Order\ndelivery',
      'promos_dia': "Today's\ndeals",
      'buscar_placeholder': 'Search dishes, restaurants...',
      'cuenta': 'ACCOUNT',
      'preferencias': 'PREFERENCES',
      'soporte': 'SUPPORT',
      'cerrar_sesion': 'Sign out',
      'cliente_desde': 'Customer since',
      'visitas': 'VISITS',
      'calif_prom': 'AVG. RATING',
      'favoritos': 'Favorites',
      'metodos_pago': 'Payment methods',
      'direcciones': 'Addresses',
      'idioma': 'Language',
      'apariencia': 'Appearance',
      'notificaciones': 'Notifications',
      'ayuda': 'Help center',
      'privacidad': 'Privacy',
      'acerca_de': 'About',
      'miembro': 'MEMBER',
      'panel': 'Dashboard',
      'analisis': 'Analytics',
      'negocio': 'Business',
      'mi_negocio': 'My business',
      'gestion_restaurante': 'RESTAURANT MANAGEMENT',
      'tu_restaurante': 'YOUR RESTAURANT',
      'tus_datos': 'YOUR INFO',
      'gestion_negocio': 'BUSINESS MANAGEMENT',
      'operaciones': 'OPERATIONS',
      'configuracion': 'SETTINGS',
      'administrador': 'ADMIN',
      'resumen_hoy': "Today's summary",
      'ventas_hoy': 'Sales today',
      'pedidos_activos': 'Active orders',
      'mesas_ocupadas': 'Occupied tables',
      'clientes_hoy': 'Customers today',
      'pedidos_recientes': 'Recent orders',
      'sin_datos_admin':
          "As orders come in, you'll see\nforecasts and metrics here.",
    },
    'pt': {
      'inicio': 'Início',
      'pedidos': 'Pedidos',
      'momento': 'Momento',
      'perfil': 'Perfil',
      'hola': 'Olá',
      'mis_pedidos': 'Meus pedidos',
      'mis_facturas': 'Minhas faturas',
      'tus_recibos': 'Seus recibos',
      'tus_facturas': 'Suas faturas',
      'historial_compras': 'Histórico das suas compras',
      'seguimiento_vivo': 'ACOMPANHAMENTO AO VIVO',
      'en_preparacion': 'EM PREPARO',
      'historial_hoy': 'HISTÓRICO DE HOJE',
      'total_hoy': 'TOTAL DE HOJE',
      'sin_pedidos': 'Ainda sem pedidos',
      'sin_pedidos_msg':
          'Quando você fizer o primeiro pedido,\nele aparecerá aqui em tempo real.',
      'explorar_menu': 'EXPLORAR CARDÁPIO',
      'sugerencia': 'SUGESTÃO PARA VOCÊ',
      'momento_ideal': 'Melhor momento',
      'prediccion_afluencia': 'PREVISÃO DE FLUXO · HOJE',
      'sin_datos': 'Ainda sem dados suficientes',
      'sin_datos_cliente':
          'Após sua primeira visita, mostraremos\nos melhores horários para vir.',
      'mejor_hora': 'MELHOR HORA SUGERIDA',
      'tendencia_semana': 'TENDÊNCIA DA SEMANA',
      'espera_promedio': 'ESPERA MÉDIA',
      'mesas_libres': 'MESAS LIVRES',
      'destacados_hoy': 'Destaques de hoje',
      'recomendados_ti': 'Recomendados para você',
      'categorias': 'Categorias',
      'ver_todos': 'Ver todos',
      'oferta_hoy': 'OFERTA DE HOJE',
      'reservar_mesa': 'Reservar\nmesa',
      'pedido_domicilio': 'Pedido em\ncasa',
      'promos_dia': 'Promoções\ndo dia',
      'buscar_placeholder': 'Pesquisar pratos, restaurantes...',
      'cuenta': 'CONTA',
      'preferencias': 'PREFERÊNCIAS',
      'soporte': 'SUPORTE',
      'cerrar_sesion': 'Sair',
      'cliente_desde': 'Cliente desde',
      'visitas': 'VISITAS',
      'calif_prom': 'AVAL. MÉDIA',
      'favoritos': 'Favoritos',
      'metodos_pago': 'Métodos de pagamento',
      'direcciones': 'Endereços',
      'idioma': 'Idioma',
      'apariencia': 'Aparência',
      'notificaciones': 'Notificações',
      'ayuda': 'Central de ajuda',
      'privacidad': 'Privacidade',
      'acerca_de': 'Sobre',
      'miembro': 'MEMBRO',
      'panel': 'Painel',
      'analisis': 'Análise',
      'negocio': 'Negócio',
      'mi_negocio': 'Meu negócio',
      'gestion_restaurante': 'GESTÃO DO RESTAURANTE',
      'tu_restaurante': 'SEU RESTAURANTE',
      'tus_datos': 'SEUS DADOS',
      'gestion_negocio': 'GESTÃO DO NEGÓCIO',
      'operaciones': 'OPERAÇÕES',
      'configuracion': 'CONFIGURAÇÕES',
      'administrador': 'ADMIN',
      'resumen_hoy': 'Resumo de hoje',
      'ventas_hoy': 'Vendas hoje',
      'pedidos_activos': 'Pedidos ativos',
      'mesas_ocupadas': 'Mesas ocupadas',
      'clientes_hoy': 'Clientes hoje',
      'pedidos_recientes': 'Pedidos recentes',
      'sin_datos_admin':
          'À medida que receber pedidos, verá\nprevisões e métricas aqui.',
    },
  };

  static String t(BuildContext context, String key) {
    final lang = AppSettingsScope.of(context).locale.languageCode;
    return _all[lang]?[key] ?? _all['es']![key] ?? key;
  }
}
